on: [push, pull_request, workflow_dispatch]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Initialize submodules

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: .

  build:
    needs: prepare
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      repo: repo
    steps:
      - name: Download repository
        uses: actions/download-artifact@v2
        with:
          name: repo
